name: Deploy to Prod

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version to deploy"
        required: true

jobs:
  test:
    uses: ./.github/workflows/tests.yml
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}

      - name: Add server to known_hosts
        run: ssh-keyscan -H ${{ vars.SERVER_IP_PROD }} >> ~/.ssh/known_hosts

      - name: Deploy to Prod via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ vars.SERVER_IP_PROD }}
          username: ${{ secrets.USER_PROD }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
          port: 22
          script: |
            cd /home/ubuntu/vitrina-back

            # Создание .env.prod с подстановкой параметров
            cat <<EOF > .env.prod
            ENV_NAME=prod
            VERSION=${{ github.event.inputs.version }}
            CR_ID=${{ vars.CR_ID }}
            APP_PORT=5000

            DB_PORT=5432
            POSTGRES_DB=${{ secrets.POSTGRES_DB_PROD }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER_PROD }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD_PROD }}
            DATABASE_URL=Host=db;Port=5432;Database=${{ secrets.POSTGRES_DB_PROD }};Username=${{ secrets.POSTGRES_USER_PROD }};Password=${{ secrets.POSTGRES_PASSWORD_PROD }}

            YANDEX_S3_ACCESS_KEY=${{ secrets.YANDEX_S3_ACCESS_KEY }}
            YANDEX_S3_SECRET_KEY=${{ secrets.YANDEX_S3_SECRET_KEY }}
            YANDEX_S3_BUCKET_NAME=${{ secrets.YANDEX_S3_BUCKET_NAME }}

            JWT_SECRET=${{ secrets.JWT_SECRET_PROD }}
            EOF

            # Обновление сервиса
            docker compose --env-file .env.prod pull app
            docker compose --env-file .env.prod up -d app

            # Очистка неиспользуемых образов
            docker image prune -af
